{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-external-secrets.serviceAccountName" . }}
  annotations:
  {{- if .Values.saAnnotations }}
    {{- toYaml .Values.saAnnotations | nindent 8 }}
  {{- end }}  
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "kubernetes-external-secrets.name" . }}
    helm.sh/chart: {{ include "kubernetes-external-secrets.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}
